version: '3'

volumes:
  signifier_local_postgres_data: {}
  signifier_local_postgres_data_backups: {}

services:
  django: &django
    user: "1000:1000"
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: signifier_local_django
    container_name: signifier_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
    volumes:
      - /home/yepdev/apps/web-signifier:/app:z
      - /home/yepdev/data/web-signifier:/output:z
      - /home/yepdev/Drive/sync/obsidian/Memex:/memex:z
      - /home/yepdev/Drive/sync/articles:/articles:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: signifier_production_postgres
    container_name: signifier_local_postgres
    volumes:
      - signifier_local_postgres_data:/var/lib/postgresql/data:Z
      - signifier_local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: signifier_local_redis

  celeryworker:
    <<: *django
    image: signifier_local_celeryworker
    container_name: signifier_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker
#    logging:
#      driver: none

  celerybeat:
    <<: *django
    image: signifier_local_celerybeat
    container_name: signifier_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: signifier_local_flower
    container_name: signifier_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
